name: loadbalancer

on:
  workflow_dispatch:

jobs:
  build-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create PEM file
        run: |
          printf "%s" "${{ secrets.SUNPO }}" > key.pem
          chmod 600 key.pem

      - name: Copy app.py
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem app.py ec2-user@34.228.165.122:/home/ec2-user/

      - name: Copy requirements.txt
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem requirements.txt ec2-user@34.228.165.122:/home/ec2-user/

      - name: Deploy and run app
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@34.228.165.122 "
          cd /home/ec2-user &&

          sudo fuser -k 5000/tcp || true &&

          if [ ! -d \"virtualenv\" ]; then
          python3 -m venv virtualenv
          fi &&

          source virtualenv/bin/activate &&

          pip install -r requirements.txt --quiet &&

          nohup python3 app.py > output.log 2>&1 &
          "
          # run in background
          nohup python3 app.py > output.log 2>&1 &
          "
